name: dio_http_client
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.0.2
  dio_http_cache:
    git:
      url: https://github.com/diohttpclient/dio-http-cache.git
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
