name: dio_http_client
description: Advanced wrapper for https://pub.dev/packages/dio
version: 0.0.1
homepage: https://github.com/diohttpclient/dio_http_client

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
